export const GET_ALL_WALLET = "GET_ALL_WALLET";
export const CREATE_WALLET = "CREATE_WALLET";
export const UPDATE_WALLET = "UPDATE_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";
export const SET_CURRENT_WALLET = "SET_CURRENT_WALLET";
export const LOAD_WALLET_PAGE = "LOAD_WALLET_PAGE";
export const FREEZE_WALLET = "FREEZE_WALLET";
export const UN_FREEZE_WALLET = "UN_FREEZE_WALLET";

export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const GET_ME = "GET_ME";

export const GET_ALL_TRANSACTION = "GET_ALL_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_TRANSACTION";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const UPDATE_WALLET_TAB = "UPDATE_WALLET_TAB";

export const CREATE_TEAM = "CREATE_TEAM";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const GET_ALL_TEAM = "GET_ALL_TEAM";

export const GET_ALL_MEMBER = "GET_ALL_MEMBER";
export const CREATE_MEMBER = "CREATE_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";

export const RESET_ROOT_STATE = "RESET_ROOT_STATE";

export const LOAD_REPORT_PAGE = "LOAD_REPORT_PAGE";
export const GET_REPORT = "GET_REPORT";
