export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const PUSH_MESSAGE = "PUSH_MESSAGE";

export const GET_ALL_WALLET_SUCCESS = "GET_ALL_WALLET_SUCCESS";
export const SET_CURRENT_WALLET_SUCCESS = "SET_CURRENT_WALLET_SUCCESS";
export const CREATE_WALLET_SUCCESS = "CREATE_WALLET_SUCCESS";
export const UPDATE_WALLET_SUCCESS = "UPDATE_WALLET_SUCCESS";
export const DELETE_WALLET_SUCCESS = "DELETE_WALLET_SUCCESS";

export const GET_ALL_TRANSACTION_SUCCESS = "GET_ALL_TRANSACTION_SUCCESS";
export const SET_TRANSACTION_FILTER = "SET_TRANSACTION_FILTER";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_FILTER";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const SET_CURRENT_TRANSACTION_SUCCESS =
  "SET_CURRENT_TRANSACTION_SUCCESS";

export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";

export const UPDATE_WALLET_TAB_SUCCESS = "UPDATE_WALLET_TAB_SUCCESS";

export const GET_ALL_TEAM_SUCCESS = "GET_ALL_TEAM_SUCCESS";

export const GET_ALL_MEMBER_SUCCESS = "GET_ALL_MEMBER_SUCCESS";

export const RESET_AUTH_STATE_SUCCESS = "RESET_AUTH_STATE_SUCCESS";
export const RESET_CATEGORY_STATE_SUCCESS = "RESET_CATEGORY_STATE_SUCCESS";
export const RESET_MEMBER_STATE_SUCCESS = "RESET_MEMBER_STATE_SUCCESS";
export const RESET_MESSAGE_STATE_SUCCESS = "RESET_MESSAGE_STATE_SUCCESS";
export const RESET_TEAM_STATE_SUCCESS = "RESET_TEAM_STATE_SUCCESS";
export const RESET_TRANSACTION_STATE_SUCCESS =
  "RESET_TRANSACTION_STATE_SUCCESS";
export const RESET_WALLET_STATE_SUCCESS = "RESET_WALLET_STATE_SUCCESS";
